sudo: required

services:
  - docker

before_install:
  - docker build -t nmhnmh/sitekicker:latest .

script:
  - echo "Done!"

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push nmhnmh/sitekicker:latest;
    fi
