sudo: required

language: python
python:
  - "3.5"
  - "3.6"
  - "nightly"

services:
  - docker

before_install:
  - export IMAGE_NAME="$TRAVIS_REPO_SLUG"
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      export IMAGE_TAG_NAME=latest;
    elif [ -n "$TRAVIS_TAG" ]; then
      export IMAGE_TAG_NAME="$TRAVIS_TAG";
    fi
  - docker build -t "$IMAGE_NAME:$IMAGE_TAG_NAME" .

script:
  - docker run --rm -t -i -v "$TRAVIS_BUILD_DIR/examples/simple-site/source" "$IMAGE_NAME:$IMAGE_TAG_NAME"
  - docker run --rm -t -i -v "$TRAVIS_BUILD_DIR/examples/simple-site/source" "$IMAGE_NAME:$IMAGE_TAG_NAME" sitekicker --full-build
  - docker run --rm -t -i -v "$TRAVIS_BUILD_DIR/examples/simple-site/source" "$IMAGE_NAME:$IMAGE_TAG_NAME" sitekicker --no-parallel
  - docker run --rm -t -i -v "$TRAVIS_BUILD_DIR/examples/simple-site/source" "$IMAGE_NAME:$IMAGE_TAG_NAME" sitekicker --full-build  --no-parallel

jobs:
  include:
    - stage: deploy
      python: 3.6
      script:
        - if [ "$TRAVIS_BRANCH" == "master" ]; then
            docker build -t $TRAVIS_REPO_SLUG:latest . ;
            docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" ;
            docker push $TRAVIS_REPO_SLUG:latest ;
          elif [ "$TRAVIS_TAG" ]; then
            docker build -t $TRAVIS_REPO_SLUG:$TRAVIS_TAG . ;
            docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" ;
            docker push $TRAVIS_REPO_SLUG:$TRAVIS_TAG ;
          fi
