sudo: required

language: python
python:
  - "3.5"
  - "3.6"
  - "nightly"

services:
  - docker

jobs:
  include:
    - stage: prepare
      before_install:
        - sudo apt-get -qq update
        - sudo apt-get -qq install -y --no-install-recommends curl python3 python3-pip python3-setuptools git ca-certificates imagemagick
        - pip3 install -e .
    - stage: test
      script:
        - pushd examples/simple-site
        - sitekicker
        - popd
    - stage: deploy
      script:
        - docker build -t nmhnmh/sitekicker:latest .
        - if [ "$TRAVIS_BRANCH" == "master" ]; then
          docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
          docker push nmhnmh/sitekicker:latest;
          fi
