sudo: required

language: python
python:
  - "3.5"
  - "3.6"
  - "nightly"

services:
  - docker

before_install:
  - docker build -t nmhnmh/sitekicker:latest .

script:
  - docker run --rm -t -i -v "$TRAVIS_BUILD_DIR/examples/simple-site:/source" nmhnmh/sitekicker:latest

jobs:
  include:
    - stage: deploy
      python: 3.6
      script:
        - if [ "$TRAVIS_BRANCH" == "master" ]; then
          docker build -t nmhnmh/sitekicker:latest .
          docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
          docker push nmhnmh/sitekicker:latest;
          else
          echo 'Only Deploy Master Branch!'
          fi
