name: build and deploy

on:
  push:
    branches:
    - master

jobs:
  lint:
    runs-on: macOS-10.14
    steps:
    - uses: actions/checkout@master
    - name: hadolint
      run: |
        brew install hadolint
        hadolint ./Dockerfile
