name: build and deploy

on:
  push:
    branches:
      - master
    tags:
      - 'v*.*.*'

jobs:

  Linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Get tag
      id: tag
      run: |
        echo ::set-env name=TAG::${GITHUB_REF#refs/tags/}
    - name: Install dependencies
      run: |
        sudo apt-get update && sudo apt-get install python3-venv -y
        curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
        source $HOME/.poetry/env
        poetry install
        poetry build
    - name: Publish to pypi.org
      # only publish when it is a tag
      if: startsWith(env.TAG, 'v')
      run: |
        source $HOME/.poetry/env
        poetry publish -u __token__ -p ${{ secrets.PYPI_TOKEN }}
    - name: Publish to Docker hub
      # only publish when it is a tag
      if: startsWith(env.TAG, 'v')
      run: |
        docker login --username nmhnmh --password ${{ secrets.DOCKER_HUB_TOKEN }}
        docker build . -t nmhnmh/sitekicker:latest
        docker tag nmhnmh/sitekicker:latest nmhnmh/sitekicker:${{ env.TAG }}
        docker push nmhnmh/sitekicker:latest
        docker push nmhnmh/sitekicker:${{ env.TAG }}